import mahotas.features
import skimage.measure
import sqlalchemy
import sqlalchemy.ext.declarative
import sqlalchemy.orm

Base = sqlalchemy.ext.declarative.declarative_base()


class Image(Base):
    __tablename__ = "images"

    id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)

    moments_central_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_1_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_4_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_4_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_4_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_4_4 = sqlalchemy.Column(sqlalchemy.Float)

    moments_hu_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_hu_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_hu_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_hu_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_hu_5 = sqlalchemy.Column(sqlalchemy.Float)
    moments_hu_6 = sqlalchemy.Column(sqlalchemy.Float)
    moments_hu_7 = sqlalchemy.Column(sqlalchemy.Float)

    moments_normalized_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_1_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_4_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_4_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_4_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_4_4 = sqlalchemy.Column(sqlalchemy.Float)

    moments_spatial_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_1_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_4 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_4_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_4_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_4_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_4_4 = sqlalchemy.Column(sqlalchemy.Float)

    moments_zernike_01_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_01_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_02_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_03_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_04_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_05_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_06_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_07_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_08_25 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_01 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_02 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_03 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_04 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_05 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_06 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_07 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_08 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_09 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_10 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_11 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_12 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_13 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_14 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_15 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_16 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_17 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_18 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_19 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_20 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_21 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_22 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_23 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_24 = sqlalchemy.Column(sqlalchemy.Float)
    moments_zernike_09_25 = sqlalchemy.Column(sqlalchemy.Float)

    texture_haralick_01_01 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_02 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_03 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_04 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_05 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_06 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_07 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_08 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_09 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_10 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_11 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_12 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_13 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_01_14 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_01 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_02 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_03 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_04 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_05 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_06 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_07 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_08 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_09 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_10 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_11 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_12 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_13 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_02_14 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_01 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_02 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_03 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_04 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_05 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_06 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_07 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_08 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_09 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_10 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_11 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_12 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_13 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_03_14 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_01 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_02 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_03 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_04 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_05 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_06 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_07 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_08 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_09 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_10 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_11 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_12 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_13 = sqlalchemy.Column(sqlalchemy.Float)
    texture_haralick_04_14 = sqlalchemy.Column(sqlalchemy.Float)

    threshold_adjacency_statistics_01 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_02 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_03 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_04 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_05 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_06 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_07 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_08 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_09 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_10 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_11 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_12 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_13 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_14 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_15 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_16 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_17 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_18 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_19 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_20 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_21 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_22 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_23 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_24 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_25 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_26 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_27 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_28 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_29 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_30 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_31 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_32 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_33 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_34 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_35 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_36 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_37 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_38 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_39 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_40 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_41 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_42 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_43 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_44 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_45 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_46 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_47 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_48 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_49 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_50 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_51 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_52 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_53 = sqlalchemy.Column(sqlalchemy.Float)
    threshold_adjacency_statistics_54 = sqlalchemy.Column(sqlalchemy.Float)

    parameter_free_threshold_adjacency_statistics_01 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_02 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_03 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_04 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_05 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_06 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_07 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_08 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_09 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_10 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_11 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_12 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_13 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_14 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_15 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_16 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_17 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_18 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_19 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_20 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_21 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_22 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_23 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_24 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_25 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_26 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_27 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_28 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_29 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_30 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_31 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_32 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_33 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_34 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_35 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_36 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_37 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_38 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_39 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_40 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_41 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_42 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_43 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_44 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_45 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_46 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_47 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_48 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_49 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_50 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_51 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_52 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_53 = sqlalchemy.Column(sqlalchemy.Float)
    parameter_free_threshold_adjacency_statistics_54 = sqlalchemy.Column(sqlalchemy.Float)

    pathname = sqlalchemy.Column(sqlalchemy.String)

    def __init__(self, pathname, data):
        self.pathname = pathname

        moments_spatial = skimage.measure.moments(data)

        moments_central = skimage.measure.moments_central(data, moments_spatial[0, 1] / moments_spatial[0, 0], moments_spatial[1, 0] / moments_spatial[0, 0])

        moments_hu = skimage.measure.moments_hu(data)

        moments_normalized = skimage.measure.moments_normalized(data)

        moments_zernike_01 = mahotas.features.zernike_moments(data, 1)
        moments_zernike_02 = mahotas.features.zernike_moments(data, 2)
        moments_zernike_03 = mahotas.features.zernike_moments(data, 3)
        moments_zernike_04 = mahotas.features.zernike_moments(data, 4)
        moments_zernike_05 = mahotas.features.zernike_moments(data, 5)
        moments_zernike_06 = mahotas.features.zernike_moments(data, 6)
        moments_zernike_07 = mahotas.features.zernike_moments(data, 7)
        moments_zernike_08 = mahotas.features.zernike_moments(data, 8)
        moments_zernike_09 = mahotas.features.zernike_moments(data, 9)

        texture_haralick = mahotas.features.haralick(data, compute_14th_feature=True)

        threshold_adjacency_statistics = mahotas.features.tas(data)

        parameter_free_threshold_adjacency_statistics = mahotas.features.pftas(data)

        self.moments_central_1_1 = moments_central[0, 0]
        self.moments_central_1_2 = moments_central[0, 1]
        self.moments_central_1_3 = moments_central[0, 2]
        self.moments_central_1_4 = moments_central[0, 3]
        self.moments_central_2_1 = moments_central[1, 0]
        self.moments_central_2_2 = moments_central[1, 1]
        self.moments_central_2_3 = moments_central[1, 2]
        self.moments_central_2_4 = moments_central[1, 3]
        self.moments_central_3_1 = moments_central[2, 0]
        self.moments_central_3_2 = moments_central[2, 1]
        self.moments_central_3_3 = moments_central[2, 2]
        self.moments_central_3_4 = moments_central[2, 3]
        self.moments_central_4_1 = moments_central[3, 0]
        self.moments_central_4_2 = moments_central[3, 1]
        self.moments_central_4_3 = moments_central[3, 2]
        self.moments_central_4_4 = moments_central[3, 3]

        self.moments_hu_1 = moments_hu[0]
        self.moments_hu_2 = moments_hu[1]
        self.moments_hu_3 = moments_hu[2]
        self.moments_hu_4 = moments_hu[3]
        self.moments_hu_5 = moments_hu[4]
        self.moments_hu_6 = moments_hu[5]
        self.moments_hu_7 = moments_hu[6]

        self.moments_normalized_1_1 = moments_normalized[0, 0]
        self.moments_normalized_1_2 = moments_normalized[0, 1]
        self.moments_normalized_1_3 = moments_normalized[0, 2]
        self.moments_normalized_1_4 = moments_normalized[0, 3]
        self.moments_normalized_2_1 = moments_normalized[1, 0]
        self.moments_normalized_2_2 = moments_normalized[1, 1]
        self.moments_normalized_2_3 = moments_normalized[1, 2]
        self.moments_normalized_2_4 = moments_normalized[1, 3]
        self.moments_normalized_3_1 = moments_normalized[2, 0]
        self.moments_normalized_3_2 = moments_normalized[2, 1]
        self.moments_normalized_3_3 = moments_normalized[2, 2]
        self.moments_normalized_3_4 = moments_normalized[2, 3]
        self.moments_normalized_4_1 = moments_normalized[3, 0]
        self.moments_normalized_4_2 = moments_normalized[3, 1]
        self.moments_normalized_4_3 = moments_normalized[3, 2]
        self.moments_normalized_4_4 = moments_normalized[3, 3]

        self.moments_spatial_1_1 = moments_spatial[0, 0]
        self.moments_spatial_1_2 = moments_spatial[0, 1]
        self.moments_spatial_1_3 = moments_spatial[0, 2]
        self.moments_spatial_1_4 = moments_spatial[0, 3]
        self.moments_spatial_2_1 = moments_spatial[1, 0]
        self.moments_spatial_2_2 = moments_spatial[1, 1]
        self.moments_spatial_2_3 = moments_spatial[1, 2]
        self.moments_spatial_2_4 = moments_spatial[1, 3]
        self.moments_spatial_3_1 = moments_spatial[2, 0]
        self.moments_spatial_3_2 = moments_spatial[2, 1]
        self.moments_spatial_3_3 = moments_spatial[2, 2]
        self.moments_spatial_3_4 = moments_spatial[2, 3]
        self.moments_spatial_4_1 = moments_spatial[3, 0]
        self.moments_spatial_4_2 = moments_spatial[3, 1]
        self.moments_spatial_4_3 = moments_spatial[3, 2]
        self.moments_spatial_4_4 = moments_spatial[3, 3]

        self.moments_zernike_01_01 = moments_zernike_01[1 - 1]
        self.moments_zernike_01_02 = moments_zernike_01[2 - 1]
        self.moments_zernike_01_03 = moments_zernike_01[3 - 1]
        self.moments_zernike_01_04 = moments_zernike_01[4 - 1]
        self.moments_zernike_01_05 = moments_zernike_01[5 - 1]
        self.moments_zernike_01_06 = moments_zernike_01[6 - 1]
        self.moments_zernike_01_07 = moments_zernike_01[7 - 1]
        self.moments_zernike_01_08 = moments_zernike_01[8 - 1]
        self.moments_zernike_01_09 = moments_zernike_01[9 - 1]
        self.moments_zernike_01_10 = moments_zernike_01[10 - 1]
        self.moments_zernike_01_11 = moments_zernike_01[11 - 1]
        self.moments_zernike_01_12 = moments_zernike_01[12 - 1]
        self.moments_zernike_01_13 = moments_zernike_01[13 - 1]
        self.moments_zernike_01_14 = moments_zernike_01[14 - 1]
        self.moments_zernike_01_15 = moments_zernike_01[15 - 1]
        self.moments_zernike_01_16 = moments_zernike_01[16 - 1]
        self.moments_zernike_01_17 = moments_zernike_01[17 - 1]
        self.moments_zernike_01_18 = moments_zernike_01[18 - 1]
        self.moments_zernike_01_19 = moments_zernike_01[19 - 1]
        self.moments_zernike_01_20 = moments_zernike_01[20 - 1]
        self.moments_zernike_01_21 = moments_zernike_01[21 - 1]
        self.moments_zernike_01_22 = moments_zernike_01[22 - 1]
        self.moments_zernike_01_23 = moments_zernike_01[23 - 1]
        self.moments_zernike_01_24 = moments_zernike_01[24 - 1]
        self.moments_zernike_01_25 = moments_zernike_01[25 - 1]
        self.moments_zernike_02_01 = moments_zernike_02[1 - 1]
        self.moments_zernike_02_02 = moments_zernike_02[2 - 1]
        self.moments_zernike_02_03 = moments_zernike_02[3 - 1]
        self.moments_zernike_02_04 = moments_zernike_02[4 - 1]
        self.moments_zernike_02_05 = moments_zernike_02[5 - 1]
        self.moments_zernike_02_06 = moments_zernike_02[6 - 1]
        self.moments_zernike_02_07 = moments_zernike_02[7 - 1]
        self.moments_zernike_02_08 = moments_zernike_02[8 - 1]
        self.moments_zernike_02_09 = moments_zernike_02[9 - 1]
        self.moments_zernike_02_10 = moments_zernike_02[10 - 1]
        self.moments_zernike_02_11 = moments_zernike_02[11 - 1]
        self.moments_zernike_02_12 = moments_zernike_02[12 - 1]
        self.moments_zernike_02_13 = moments_zernike_02[13 - 1]
        self.moments_zernike_02_14 = moments_zernike_02[14 - 1]
        self.moments_zernike_02_15 = moments_zernike_02[15 - 1]
        self.moments_zernike_02_16 = moments_zernike_02[16 - 1]
        self.moments_zernike_02_17 = moments_zernike_02[17 - 1]
        self.moments_zernike_02_18 = moments_zernike_02[18 - 1]
        self.moments_zernike_02_19 = moments_zernike_02[19 - 1]
        self.moments_zernike_02_20 = moments_zernike_02[20 - 1]
        self.moments_zernike_02_21 = moments_zernike_02[21 - 1]
        self.moments_zernike_02_22 = moments_zernike_02[22 - 1]
        self.moments_zernike_02_23 = moments_zernike_02[23 - 1]
        self.moments_zernike_02_24 = moments_zernike_02[24 - 1]
        self.moments_zernike_02_25 = moments_zernike_02[25 - 1]
        self.moments_zernike_03_01 = moments_zernike_03[1 - 1]
        self.moments_zernike_03_02 = moments_zernike_03[2 - 1]
        self.moments_zernike_03_03 = moments_zernike_03[3 - 1]
        self.moments_zernike_03_04 = moments_zernike_03[4 - 1]
        self.moments_zernike_03_05 = moments_zernike_03[5 - 1]
        self.moments_zernike_03_06 = moments_zernike_03[6 - 1]
        self.moments_zernike_03_07 = moments_zernike_03[7 - 1]
        self.moments_zernike_03_08 = moments_zernike_03[8 - 1]
        self.moments_zernike_03_09 = moments_zernike_03[9 - 1]
        self.moments_zernike_03_10 = moments_zernike_03[10 - 1]
        self.moments_zernike_03_11 = moments_zernike_03[11 - 1]
        self.moments_zernike_03_12 = moments_zernike_03[12 - 1]
        self.moments_zernike_03_13 = moments_zernike_03[13 - 1]
        self.moments_zernike_03_14 = moments_zernike_03[14 - 1]
        self.moments_zernike_03_15 = moments_zernike_03[15 - 1]
        self.moments_zernike_03_16 = moments_zernike_03[16 - 1]
        self.moments_zernike_03_17 = moments_zernike_03[17 - 1]
        self.moments_zernike_03_18 = moments_zernike_03[18 - 1]
        self.moments_zernike_03_19 = moments_zernike_03[19 - 1]
        self.moments_zernike_03_20 = moments_zernike_03[20 - 1]
        self.moments_zernike_03_21 = moments_zernike_03[21 - 1]
        self.moments_zernike_03_22 = moments_zernike_03[22 - 1]
        self.moments_zernike_03_23 = moments_zernike_03[23 - 1]
        self.moments_zernike_03_24 = moments_zernike_03[24 - 1]
        self.moments_zernike_03_25 = moments_zernike_03[25 - 1]
        self.moments_zernike_04_01 = moments_zernike_04[1 - 1]
        self.moments_zernike_04_02 = moments_zernike_04[2 - 1]
        self.moments_zernike_04_03 = moments_zernike_04[3 - 1]
        self.moments_zernike_04_04 = moments_zernike_04[4 - 1]
        self.moments_zernike_04_05 = moments_zernike_04[5 - 1]
        self.moments_zernike_04_06 = moments_zernike_04[6 - 1]
        self.moments_zernike_04_07 = moments_zernike_04[7 - 1]
        self.moments_zernike_04_08 = moments_zernike_04[8 - 1]
        self.moments_zernike_04_09 = moments_zernike_04[9 - 1]
        self.moments_zernike_04_10 = moments_zernike_04[10 - 1]
        self.moments_zernike_04_11 = moments_zernike_04[11 - 1]
        self.moments_zernike_04_12 = moments_zernike_04[12 - 1]
        self.moments_zernike_04_13 = moments_zernike_04[13 - 1]
        self.moments_zernike_04_14 = moments_zernike_04[14 - 1]
        self.moments_zernike_04_15 = moments_zernike_04[15 - 1]
        self.moments_zernike_04_16 = moments_zernike_04[16 - 1]
        self.moments_zernike_04_17 = moments_zernike_04[17 - 1]
        self.moments_zernike_04_18 = moments_zernike_04[18 - 1]
        self.moments_zernike_04_19 = moments_zernike_04[19 - 1]
        self.moments_zernike_04_20 = moments_zernike_04[20 - 1]
        self.moments_zernike_04_21 = moments_zernike_04[21 - 1]
        self.moments_zernike_04_22 = moments_zernike_04[22 - 1]
        self.moments_zernike_04_23 = moments_zernike_04[23 - 1]
        self.moments_zernike_04_24 = moments_zernike_04[24 - 1]
        self.moments_zernike_04_25 = moments_zernike_04[25 - 1]
        self.moments_zernike_05_01 = moments_zernike_05[1 - 1]
        self.moments_zernike_05_02 = moments_zernike_05[2 - 1]
        self.moments_zernike_05_03 = moments_zernike_05[3 - 1]
        self.moments_zernike_05_04 = moments_zernike_05[4 - 1]
        self.moments_zernike_05_05 = moments_zernike_05[5 - 1]
        self.moments_zernike_05_06 = moments_zernike_05[6 - 1]
        self.moments_zernike_05_07 = moments_zernike_05[7 - 1]
        self.moments_zernike_05_08 = moments_zernike_05[8 - 1]
        self.moments_zernike_05_09 = moments_zernike_05[9 - 1]
        self.moments_zernike_05_10 = moments_zernike_05[10 - 1]
        self.moments_zernike_05_11 = moments_zernike_05[11 - 1]
        self.moments_zernike_05_12 = moments_zernike_05[12 - 1]
        self.moments_zernike_05_13 = moments_zernike_05[13 - 1]
        self.moments_zernike_05_14 = moments_zernike_05[14 - 1]
        self.moments_zernike_05_15 = moments_zernike_05[15 - 1]
        self.moments_zernike_05_16 = moments_zernike_05[16 - 1]
        self.moments_zernike_05_17 = moments_zernike_05[17 - 1]
        self.moments_zernike_05_18 = moments_zernike_05[18 - 1]
        self.moments_zernike_05_19 = moments_zernike_05[19 - 1]
        self.moments_zernike_05_20 = moments_zernike_05[20 - 1]
        self.moments_zernike_05_21 = moments_zernike_05[21 - 1]
        self.moments_zernike_05_22 = moments_zernike_05[22 - 1]
        self.moments_zernike_05_23 = moments_zernike_05[23 - 1]
        self.moments_zernike_05_24 = moments_zernike_05[24 - 1]
        self.moments_zernike_05_25 = moments_zernike_05[25 - 1]
        self.moments_zernike_06_01 = moments_zernike_06[ 1 - 1]
        self.moments_zernike_06_02 = moments_zernike_06[ 2 - 1]
        self.moments_zernike_06_03 = moments_zernike_06[ 3 - 1]
        self.moments_zernike_06_04 = moments_zernike_06[ 4 - 1]
        self.moments_zernike_06_05 = moments_zernike_06[ 5 - 1]
        self.moments_zernike_06_06 = moments_zernike_06[ 6 - 1]
        self.moments_zernike_06_07 = moments_zernike_06[ 7 - 1]
        self.moments_zernike_06_08 = moments_zernike_06[ 8 - 1]
        self.moments_zernike_06_09 = moments_zernike_06[ 9 - 1]
        self.moments_zernike_06_10 = moments_zernike_06[10 - 1]
        self.moments_zernike_06_11 = moments_zernike_06[11 - 1]
        self.moments_zernike_06_12 = moments_zernike_06[12 - 1]
        self.moments_zernike_06_13 = moments_zernike_06[13 - 1]
        self.moments_zernike_06_14 = moments_zernike_06[14 - 1]
        self.moments_zernike_06_15 = moments_zernike_06[15 - 1]
        self.moments_zernike_06_16 = moments_zernike_06[16 - 1]
        self.moments_zernike_06_17 = moments_zernike_06[17 - 1]
        self.moments_zernike_06_18 = moments_zernike_06[18 - 1]
        self.moments_zernike_06_19 = moments_zernike_06[19 - 1]
        self.moments_zernike_06_20 = moments_zernike_06[20 - 1]
        self.moments_zernike_06_21 = moments_zernike_06[21 - 1]
        self.moments_zernike_06_22 = moments_zernike_06[22 - 1]
        self.moments_zernike_06_23 = moments_zernike_06[23 - 1]
        self.moments_zernike_06_24 = moments_zernike_06[24 - 1]
        self.moments_zernike_06_25 = moments_zernike_06[25 - 1]
        self.moments_zernike_07_01 = moments_zernike_07[ 1 - 1]
        self.moments_zernike_07_02 = moments_zernike_07[ 2 - 1]
        self.moments_zernike_07_03 = moments_zernike_07[ 3 - 1]
        self.moments_zernike_07_04 = moments_zernike_07[ 4 - 1]
        self.moments_zernike_07_05 = moments_zernike_07[ 5 - 1]
        self.moments_zernike_07_06 = moments_zernike_07[ 6 - 1]
        self.moments_zernike_07_07 = moments_zernike_07[ 7 - 1]
        self.moments_zernike_07_08 = moments_zernike_07[ 8 - 1]
        self.moments_zernike_07_09 = moments_zernike_07[ 9 - 1]
        self.moments_zernike_07_10 = moments_zernike_07[10 - 1]
        self.moments_zernike_07_11 = moments_zernike_07[11 - 1]
        self.moments_zernike_07_12 = moments_zernike_07[12 - 1]
        self.moments_zernike_07_13 = moments_zernike_07[13 - 1]
        self.moments_zernike_07_14 = moments_zernike_07[14 - 1]
        self.moments_zernike_07_15 = moments_zernike_07[15 - 1]
        self.moments_zernike_07_16 = moments_zernike_07[16 - 1]
        self.moments_zernike_07_17 = moments_zernike_07[17 - 1]
        self.moments_zernike_07_18 = moments_zernike_07[18 - 1]
        self.moments_zernike_07_19 = moments_zernike_07[19 - 1]
        self.moments_zernike_07_20 = moments_zernike_07[20 - 1]
        self.moments_zernike_07_21 = moments_zernike_07[21 - 1]
        self.moments_zernike_07_22 = moments_zernike_07[22 - 1]
        self.moments_zernike_07_23 = moments_zernike_07[23 - 1]
        self.moments_zernike_07_24 = moments_zernike_07[24 - 1]
        self.moments_zernike_07_25 = moments_zernike_07[25 - 1]
        self.moments_zernike_08_01 = moments_zernike_08[ 1 - 1]
        self.moments_zernike_08_02 = moments_zernike_08[ 2 - 1]
        self.moments_zernike_08_03 = moments_zernike_08[ 3 - 1]
        self.moments_zernike_08_04 = moments_zernike_08[ 4 - 1]
        self.moments_zernike_08_05 = moments_zernike_08[ 5 - 1]
        self.moments_zernike_08_06 = moments_zernike_08[ 6 - 1]
        self.moments_zernike_08_07 = moments_zernike_08[ 7 - 1]
        self.moments_zernike_08_08 = moments_zernike_08[ 8 - 1]
        self.moments_zernike_08_09 = moments_zernike_08[ 9 - 1]
        self.moments_zernike_08_10 = moments_zernike_08[10 - 1]
        self.moments_zernike_08_11 = moments_zernike_08[11 - 1]
        self.moments_zernike_08_12 = moments_zernike_08[12 - 1]
        self.moments_zernike_08_13 = moments_zernike_08[13 - 1]
        self.moments_zernike_08_14 = moments_zernike_08[14 - 1]
        self.moments_zernike_08_15 = moments_zernike_08[15 - 1]
        self.moments_zernike_08_16 = moments_zernike_08[16 - 1]
        self.moments_zernike_08_17 = moments_zernike_08[17 - 1]
        self.moments_zernike_08_18 = moments_zernike_08[18 - 1]
        self.moments_zernike_08_19 = moments_zernike_08[19 - 1]
        self.moments_zernike_08_20 = moments_zernike_08[20 - 1]
        self.moments_zernike_08_21 = moments_zernike_08[21 - 1]
        self.moments_zernike_08_22 = moments_zernike_08[22 - 1]
        self.moments_zernike_08_23 = moments_zernike_08[23 - 1]
        self.moments_zernike_08_24 = moments_zernike_08[24 - 1]
        self.moments_zernike_08_25 = moments_zernike_08[25 - 1]
        self.moments_zernike_09_01 = moments_zernike_09[ 1 - 1]
        self.moments_zernike_09_02 = moments_zernike_09[ 2 - 1]
        self.moments_zernike_09_03 = moments_zernike_09[ 3 - 1]
        self.moments_zernike_09_04 = moments_zernike_09[ 4 - 1]
        self.moments_zernike_09_05 = moments_zernike_09[ 5 - 1]
        self.moments_zernike_09_06 = moments_zernike_09[ 6 - 1]
        self.moments_zernike_09_07 = moments_zernike_09[ 7 - 1]
        self.moments_zernike_09_08 = moments_zernike_09[ 8 - 1]
        self.moments_zernike_09_09 = moments_zernike_09[ 9 - 1]
        self.moments_zernike_09_10 = moments_zernike_09[10 - 1]
        self.moments_zernike_09_11 = moments_zernike_09[11 - 1]
        self.moments_zernike_09_12 = moments_zernike_09[12 - 1]
        self.moments_zernike_09_13 = moments_zernike_09[13 - 1]
        self.moments_zernike_09_14 = moments_zernike_09[14 - 1]
        self.moments_zernike_09_15 = moments_zernike_09[15 - 1]
        self.moments_zernike_09_16 = moments_zernike_09[16 - 1]
        self.moments_zernike_09_17 = moments_zernike_09[17 - 1]
        self.moments_zernike_09_18 = moments_zernike_09[18 - 1]
        self.moments_zernike_09_19 = moments_zernike_09[19 - 1]
        self.moments_zernike_09_20 = moments_zernike_09[20 - 1]
        self.moments_zernike_09_21 = moments_zernike_09[21 - 1]
        self.moments_zernike_09_22 = moments_zernike_09[22 - 1]
        self.moments_zernike_09_23 = moments_zernike_09[23 - 1]
        self.moments_zernike_09_24 = moments_zernike_09[24 - 1]
        self.moments_zernike_09_25 = moments_zernike_09[25 - 1]

        self.texture_haralick_01_01 = texture_haralick[0, 0]
        self.texture_haralick_01_02 = texture_haralick[0, 1]
        self.texture_haralick_01_03 = texture_haralick[0, 2]
        self.texture_haralick_01_04 = texture_haralick[0, 3]
        self.texture_haralick_01_05 = texture_haralick[0, 4]
        self.texture_haralick_01_06 = texture_haralick[0, 5]
        self.texture_haralick_01_07 = texture_haralick[0, 6]
        self.texture_haralick_01_08 = texture_haralick[0, 7]
        self.texture_haralick_01_09 = texture_haralick[0, 8]
        self.texture_haralick_01_10 = texture_haralick[0, 9]
        self.texture_haralick_01_11 = texture_haralick[0, 10]
        self.texture_haralick_01_12 = texture_haralick[0, 11]
        self.texture_haralick_01_13 = texture_haralick[0, 12]
        self.texture_haralick_01_14 = texture_haralick[0, 13]
        self.texture_haralick_02_01 = texture_haralick[1,  0]
        self.texture_haralick_02_02 = texture_haralick[1,  1]
        self.texture_haralick_02_03 = texture_haralick[1,  2]
        self.texture_haralick_02_04 = texture_haralick[1,  3]
        self.texture_haralick_02_05 = texture_haralick[1,  4]
        self.texture_haralick_02_06 = texture_haralick[1,  5]
        self.texture_haralick_02_07 = texture_haralick[1,  6]
        self.texture_haralick_02_08 = texture_haralick[1,  7]
        self.texture_haralick_02_09 = texture_haralick[1,  8]
        self.texture_haralick_02_10 = texture_haralick[1,  9]
        self.texture_haralick_02_11 = texture_haralick[1, 10]
        self.texture_haralick_02_12 = texture_haralick[1, 11]
        self.texture_haralick_02_13 = texture_haralick[1, 12]
        self.texture_haralick_02_14 = texture_haralick[1, 13]
        self.texture_haralick_03_01 = texture_haralick[2,  0]
        self.texture_haralick_03_02 = texture_haralick[2,  1]
        self.texture_haralick_03_03 = texture_haralick[2,  2]
        self.texture_haralick_03_04 = texture_haralick[2,  3]
        self.texture_haralick_03_05 = texture_haralick[2,  4]
        self.texture_haralick_03_06 = texture_haralick[2,  5]
        self.texture_haralick_03_07 = texture_haralick[2,  6]
        self.texture_haralick_03_08 = texture_haralick[2,  7]
        self.texture_haralick_03_09 = texture_haralick[2,  8]
        self.texture_haralick_03_10 = texture_haralick[2,  9]
        self.texture_haralick_03_11 = texture_haralick[2, 10]
        self.texture_haralick_03_12 = texture_haralick[2, 11]
        self.texture_haralick_03_13 = texture_haralick[2, 12]
        self.texture_haralick_03_14 = texture_haralick[2, 13]
        self.texture_haralick_04_01 = texture_haralick[3,  0]
        self.texture_haralick_04_02 = texture_haralick[3,  1]
        self.texture_haralick_04_03 = texture_haralick[3,  2]
        self.texture_haralick_04_04 = texture_haralick[3,  3]
        self.texture_haralick_04_05 = texture_haralick[3,  4]
        self.texture_haralick_04_06 = texture_haralick[3,  5]
        self.texture_haralick_04_07 = texture_haralick[3,  6]
        self.texture_haralick_04_08 = texture_haralick[3,  7]
        self.texture_haralick_04_09 = texture_haralick[3,  8]
        self.texture_haralick_04_10 = texture_haralick[3,  9]
        self.texture_haralick_04_11 = texture_haralick[3, 10]
        self.texture_haralick_04_12 = texture_haralick[3, 11]
        self.texture_haralick_04_13 = texture_haralick[3, 12]
        self.texture_haralick_04_14 = texture_haralick[3, 13]

        self.threshold_adjacency_statistics_01 = threshold_adjacency_statistics[ 0]
        self.threshold_adjacency_statistics_02 = threshold_adjacency_statistics[ 1]
        self.threshold_adjacency_statistics_03 = threshold_adjacency_statistics[ 2]
        self.threshold_adjacency_statistics_04 = threshold_adjacency_statistics[ 3]
        self.threshold_adjacency_statistics_05 = threshold_adjacency_statistics[ 4]
        self.threshold_adjacency_statistics_06 = threshold_adjacency_statistics[ 5]
        self.threshold_adjacency_statistics_07 = threshold_adjacency_statistics[ 6]
        self.threshold_adjacency_statistics_08 = threshold_adjacency_statistics[ 7]
        self.threshold_adjacency_statistics_09 = threshold_adjacency_statistics[ 8]
        self.threshold_adjacency_statistics_10 = threshold_adjacency_statistics[ 9]
        self.threshold_adjacency_statistics_11 = threshold_adjacency_statistics[10]
        self.threshold_adjacency_statistics_12 = threshold_adjacency_statistics[11]
        self.threshold_adjacency_statistics_13 = threshold_adjacency_statistics[12]
        self.threshold_adjacency_statistics_14 = threshold_adjacency_statistics[13]
        self.threshold_adjacency_statistics_15 = threshold_adjacency_statistics[14]
        self.threshold_adjacency_statistics_16 = threshold_adjacency_statistics[15]
        self.threshold_adjacency_statistics_17 = threshold_adjacency_statistics[16]
        self.threshold_adjacency_statistics_18 = threshold_adjacency_statistics[17]
        self.threshold_adjacency_statistics_19 = threshold_adjacency_statistics[18]
        self.threshold_adjacency_statistics_20 = threshold_adjacency_statistics[19]
        self.threshold_adjacency_statistics_21 = threshold_adjacency_statistics[20]
        self.threshold_adjacency_statistics_22 = threshold_adjacency_statistics[21]
        self.threshold_adjacency_statistics_23 = threshold_adjacency_statistics[22]
        self.threshold_adjacency_statistics_24 = threshold_adjacency_statistics[23]
        self.threshold_adjacency_statistics_25 = threshold_adjacency_statistics[24]
        self.threshold_adjacency_statistics_26 = threshold_adjacency_statistics[25]
        self.threshold_adjacency_statistics_27 = threshold_adjacency_statistics[26]
        self.threshold_adjacency_statistics_28 = threshold_adjacency_statistics[27]
        self.threshold_adjacency_statistics_29 = threshold_adjacency_statistics[28]
        self.threshold_adjacency_statistics_30 = threshold_adjacency_statistics[29]
        self.threshold_adjacency_statistics_31 = threshold_adjacency_statistics[30]
        self.threshold_adjacency_statistics_32 = threshold_adjacency_statistics[31]
        self.threshold_adjacency_statistics_33 = threshold_adjacency_statistics[32]
        self.threshold_adjacency_statistics_34 = threshold_adjacency_statistics[33]
        self.threshold_adjacency_statistics_35 = threshold_adjacency_statistics[34]
        self.threshold_adjacency_statistics_36 = threshold_adjacency_statistics[35]
        self.threshold_adjacency_statistics_37 = threshold_adjacency_statistics[36]
        self.threshold_adjacency_statistics_38 = threshold_adjacency_statistics[37]
        self.threshold_adjacency_statistics_39 = threshold_adjacency_statistics[38]
        self.threshold_adjacency_statistics_40 = threshold_adjacency_statistics[39]
        self.threshold_adjacency_statistics_41 = threshold_adjacency_statistics[40]
        self.threshold_adjacency_statistics_42 = threshold_adjacency_statistics[41]
        self.threshold_adjacency_statistics_43 = threshold_adjacency_statistics[42]
        self.threshold_adjacency_statistics_44 = threshold_adjacency_statistics[43]
        self.threshold_adjacency_statistics_45 = threshold_adjacency_statistics[44]
        self.threshold_adjacency_statistics_46 = threshold_adjacency_statistics[45]
        self.threshold_adjacency_statistics_47 = threshold_adjacency_statistics[46]
        self.threshold_adjacency_statistics_48 = threshold_adjacency_statistics[47]
        self.threshold_adjacency_statistics_49 = threshold_adjacency_statistics[48]
        self.threshold_adjacency_statistics_50 = threshold_adjacency_statistics[49]
        self.threshold_adjacency_statistics_51 = threshold_adjacency_statistics[50]
        self.threshold_adjacency_statistics_52 = threshold_adjacency_statistics[51]
        self.threshold_adjacency_statistics_53 = threshold_adjacency_statistics[52]
        self.threshold_adjacency_statistics_54 = threshold_adjacency_statistics[53]

        self.parameter_free_threshold_adjacency_statistics_01 = parameter_free_threshold_adjacency_statistics[ 0]
        self.parameter_free_threshold_adjacency_statistics_02 = parameter_free_threshold_adjacency_statistics[ 1]
        self.parameter_free_threshold_adjacency_statistics_03 = parameter_free_threshold_adjacency_statistics[ 2]
        self.parameter_free_threshold_adjacency_statistics_04 = parameter_free_threshold_adjacency_statistics[ 3]
        self.parameter_free_threshold_adjacency_statistics_05 = parameter_free_threshold_adjacency_statistics[ 4]
        self.parameter_free_threshold_adjacency_statistics_06 = parameter_free_threshold_adjacency_statistics[ 5]
        self.parameter_free_threshold_adjacency_statistics_07 = parameter_free_threshold_adjacency_statistics[ 6]
        self.parameter_free_threshold_adjacency_statistics_08 = parameter_free_threshold_adjacency_statistics[ 7]
        self.parameter_free_threshold_adjacency_statistics_09 = parameter_free_threshold_adjacency_statistics[ 8]
        self.parameter_free_threshold_adjacency_statistics_10 = parameter_free_threshold_adjacency_statistics[ 9]
        self.parameter_free_threshold_adjacency_statistics_11 = parameter_free_threshold_adjacency_statistics[10]
        self.parameter_free_threshold_adjacency_statistics_12 = parameter_free_threshold_adjacency_statistics[11]
        self.parameter_free_threshold_adjacency_statistics_13 = parameter_free_threshold_adjacency_statistics[12]
        self.parameter_free_threshold_adjacency_statistics_14 = parameter_free_threshold_adjacency_statistics[13]
        self.parameter_free_threshold_adjacency_statistics_15 = parameter_free_threshold_adjacency_statistics[14]
        self.parameter_free_threshold_adjacency_statistics_16 = parameter_free_threshold_adjacency_statistics[15]
        self.parameter_free_threshold_adjacency_statistics_17 = parameter_free_threshold_adjacency_statistics[16]
        self.parameter_free_threshold_adjacency_statistics_18 = parameter_free_threshold_adjacency_statistics[17]
        self.parameter_free_threshold_adjacency_statistics_19 = parameter_free_threshold_adjacency_statistics[18]
        self.parameter_free_threshold_adjacency_statistics_20 = parameter_free_threshold_adjacency_statistics[19]
        self.parameter_free_threshold_adjacency_statistics_21 = parameter_free_threshold_adjacency_statistics[20]
        self.parameter_free_threshold_adjacency_statistics_22 = parameter_free_threshold_adjacency_statistics[21]
        self.parameter_free_threshold_adjacency_statistics_23 = parameter_free_threshold_adjacency_statistics[22]
        self.parameter_free_threshold_adjacency_statistics_24 = parameter_free_threshold_adjacency_statistics[23]
        self.parameter_free_threshold_adjacency_statistics_25 = parameter_free_threshold_adjacency_statistics[24]
        self.parameter_free_threshold_adjacency_statistics_26 = parameter_free_threshold_adjacency_statistics[25]
        self.parameter_free_threshold_adjacency_statistics_27 = parameter_free_threshold_adjacency_statistics[26]
        self.parameter_free_threshold_adjacency_statistics_28 = parameter_free_threshold_adjacency_statistics[27]
        self.parameter_free_threshold_adjacency_statistics_29 = parameter_free_threshold_adjacency_statistics[28]
        self.parameter_free_threshold_adjacency_statistics_30 = parameter_free_threshold_adjacency_statistics[29]
        self.parameter_free_threshold_adjacency_statistics_31 = parameter_free_threshold_adjacency_statistics[30]
        self.parameter_free_threshold_adjacency_statistics_32 = parameter_free_threshold_adjacency_statistics[31]
        self.parameter_free_threshold_adjacency_statistics_33 = parameter_free_threshold_adjacency_statistics[32]
        self.parameter_free_threshold_adjacency_statistics_34 = parameter_free_threshold_adjacency_statistics[33]
        self.parameter_free_threshold_adjacency_statistics_35 = parameter_free_threshold_adjacency_statistics[34]
        self.parameter_free_threshold_adjacency_statistics_36 = parameter_free_threshold_adjacency_statistics[35]
        self.parameter_free_threshold_adjacency_statistics_37 = parameter_free_threshold_adjacency_statistics[36]
        self.parameter_free_threshold_adjacency_statistics_38 = parameter_free_threshold_adjacency_statistics[37]
        self.parameter_free_threshold_adjacency_statistics_39 = parameter_free_threshold_adjacency_statistics[38]
        self.parameter_free_threshold_adjacency_statistics_40 = parameter_free_threshold_adjacency_statistics[39]
        self.parameter_free_threshold_adjacency_statistics_41 = parameter_free_threshold_adjacency_statistics[40]
        self.parameter_free_threshold_adjacency_statistics_42 = parameter_free_threshold_adjacency_statistics[41]
        self.parameter_free_threshold_adjacency_statistics_43 = parameter_free_threshold_adjacency_statistics[42]
        self.parameter_free_threshold_adjacency_statistics_44 = parameter_free_threshold_adjacency_statistics[43]
        self.parameter_free_threshold_adjacency_statistics_45 = parameter_free_threshold_adjacency_statistics[44]
        self.parameter_free_threshold_adjacency_statistics_46 = parameter_free_threshold_adjacency_statistics[45]
        self.parameter_free_threshold_adjacency_statistics_47 = parameter_free_threshold_adjacency_statistics[46]
        self.parameter_free_threshold_adjacency_statistics_48 = parameter_free_threshold_adjacency_statistics[47]
        self.parameter_free_threshold_adjacency_statistics_49 = parameter_free_threshold_adjacency_statistics[48]
        self.parameter_free_threshold_adjacency_statistics_50 = parameter_free_threshold_adjacency_statistics[49]
        self.parameter_free_threshold_adjacency_statistics_51 = parameter_free_threshold_adjacency_statistics[50]
        self.parameter_free_threshold_adjacency_statistics_52 = parameter_free_threshold_adjacency_statistics[51]
        self.parameter_free_threshold_adjacency_statistics_53 = parameter_free_threshold_adjacency_statistics[52]
        self.parameter_free_threshold_adjacency_statistics_54 = parameter_free_threshold_adjacency_statistics[53]


class Instance(Base):
    __tablename__ = "instances"

    id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)

    axis_major = sqlalchemy.Column(sqlalchemy.Float)

    bounding_box_x1 = sqlalchemy.Column(sqlalchemy.Float)
    bounding_box_x2 = sqlalchemy.Column(sqlalchemy.Float)
    bounding_box_y1 = sqlalchemy.Column(sqlalchemy.Float)
    bounding_box_y2 = sqlalchemy.Column(sqlalchemy.Float)

    centroid_weighted_local_x = sqlalchemy.Column(sqlalchemy.Float)
    centroid_weighted_local_y = sqlalchemy.Column(sqlalchemy.Float)

    centroid_weighted_x = sqlalchemy.Column(sqlalchemy.Float)
    centroid_weighted_y = sqlalchemy.Column(sqlalchemy.Float)

    centroid_x = sqlalchemy.Column(sqlalchemy.Float)
    centroid_y = sqlalchemy.Column(sqlalchemy.Float)

    eccentricity = sqlalchemy.Column(sqlalchemy.Float)

    equivalent_diameter = sqlalchemy.Column(sqlalchemy.Float)

    euler_number = sqlalchemy.Column(sqlalchemy.Float)

    extent = sqlalchemy.Column(sqlalchemy.Float)

    image_pathname = sqlalchemy.Column(sqlalchemy.String)

    index = sqlalchemy.Column(sqlalchemy.Integer)

    inertia_tensor_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    inertia_tensor_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    inertia_tensor_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    inertia_tensor_2_2 = sqlalchemy.Column(sqlalchemy.Float)

    inertia_tensor_eigvals_1 = sqlalchemy.Column(sqlalchemy.Float)
    inertia_tensor_eigvals_2 = sqlalchemy.Column(sqlalchemy.Float)

    intensity_maximum = sqlalchemy.Column(sqlalchemy.Float)
    intensity_mean = sqlalchemy.Column(sqlalchemy.Float)
    intensity_minimum = sqlalchemy.Column(sqlalchemy.Float)

    label_pathname = sqlalchemy.Column(sqlalchemy.String)

    moments_central_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_central_3_3 = sqlalchemy.Column(sqlalchemy.Float)

    moments_normalized_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_normalized_3_3 = sqlalchemy.Column(sqlalchemy.Float)

    moments_spatial_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_spatial_3_3 = sqlalchemy.Column(sqlalchemy.Float)

    moments_weighted_normalized_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_normalized_3_3 = sqlalchemy.Column(sqlalchemy.Float)

    moments_weighted_spatial_1_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_1_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_1_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_2_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_2_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_2_3 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_3_1 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_3_2 = sqlalchemy.Column(sqlalchemy.Float)
    moments_weighted_spatial_3_3 = sqlalchemy.Column(sqlalchemy.Float)

    orientation = sqlalchemy.Column(sqlalchemy.Float)

    perimeter = sqlalchemy.Column(sqlalchemy.Float)

    solidity = sqlalchemy.Column(sqlalchemy.Float)

    def __init__(self, instance):
        self.area = instance.area

        self.axis_major = instance.minor_axis_length

        self.bounding_box_x1 = instance.bbox[0]
        self.bounding_box_x2 = instance.bbox[1]
        self.bounding_box_y1 = instance.bbox[2]
        self.bounding_box_y2 = instance.bbox[3]

        self.centroid_weighted_local_x = instance.weighted_local_centroid[0]
        self.centroid_weighted_local_y = instance.weighted_local_centroid[1]

        self.centroid_weighted_x = instance.weighted_centroid[0]
        self.centroid_weighted_y = instance.weighted_centroid[1]

        self.centroid_x = instance.centroid[0]
        self.centroid_y = instance.centroid[1]

        self.convex_area = instance.convex_area

        self.eccentricity = instance.eccentricity

        self.equivalent_diameter = instance.equivalent_diameter

        self.euler_number = instance.euler_number

        self.extent = instance.extent

        self.filled_area = instance.filled_area

        self.index = instance.label

        self.inertia_tensor_1_1 = instance.inertia_tensor[0, 0]
        self.inertia_tensor_1_2 = instance.inertia_tensor[0, 1]
        self.inertia_tensor_2_1 = instance.inertia_tensor[1, 0]
        self.inertia_tensor_2_2 = instance.inertia_tensor[1, 1]

        self.inertia_tensor_eigvals_1 = instance.inertia_tensor_eigvals[0]
        self.inertia_tensor_eigvals_2 = instance.inertia_tensor_eigvals[1]

        self.intensity_maximum = instance.max_intensity
        self.intensity_mean = instance.mean_intensity
        self.intensity_minimum = instance.min_intensity

        self.moments_central_1_1 = instance.moments_central[0, 0]
        self.moments_central_1_2 = instance.moments_central[0, 1]
        self.moments_central_1_3 = instance.moments_central[0, 2]
        self.moments_central_2_1 = instance.moments_central[1, 0]
        self.moments_central_2_2 = instance.moments_central[1, 1]
        self.moments_central_2_3 = instance.moments_central[1, 2]
        self.moments_central_3_1 = instance.moments_central[2, 0]
        self.moments_central_3_2 = instance.moments_central[2, 1]
        self.moments_central_3_3 = instance.moments_central[2, 2]

        self.moments_normalized_1_1 = instance.moments_normalized[0, 0]
        self.moments_normalized_1_2 = instance.moments_normalized[0, 1]
        self.moments_normalized_1_3 = instance.moments_normalized[0, 2]
        self.moments_normalized_2_1 = instance.moments_normalized[1, 0]
        self.moments_normalized_2_2 = instance.moments_normalized[1, 1]
        self.moments_normalized_2_3 = instance.moments_normalized[1, 2]
        self.moments_normalized_3_1 = instance.moments_normalized[2, 0]
        self.moments_normalized_3_2 = instance.moments_normalized[2, 1]
        self.moments_normalized_3_3 = instance.moments_normalized[2, 2]

        self.moments_spatial_1_1 = instance.moments[0, 0]
        self.moments_spatial_1_2 = instance.moments[0, 1]
        self.moments_spatial_1_3 = instance.moments[0, 2]
        self.moments_spatial_2_1 = instance.moments[1, 0]
        self.moments_spatial_2_2 = instance.moments[1, 1]
        self.moments_spatial_2_3 = instance.moments[1, 2]
        self.moments_spatial_3_1 = instance.moments[2, 0]
        self.moments_spatial_3_2 = instance.moments[2, 1]
        self.moments_spatial_3_3 = instance.moments[2, 2]

        self.moments_weighted_central_1_1 = instance.weighted_moments_central[0, 0]
        self.moments_weighted_central_1_2 = instance.weighted_moments_central[0, 1]
        self.moments_weighted_central_1_3 = instance.weighted_moments_central[0, 2]
        self.moments_weighted_central_2_1 = instance.weighted_moments_central[1, 0]
        self.moments_weighted_central_2_2 = instance.weighted_moments_central[1, 1]
        self.moments_weighted_central_2_3 = instance.weighted_moments_central[1, 2]
        self.moments_weighted_central_3_1 = instance.weighted_moments_central[2, 0]
        self.moments_weighted_central_3_2 = instance.weighted_moments_central[2, 1]
        self.moments_weighted_central_3_3 = instance.weighted_moments_central[2, 2]

        self.moments_weighted_normalized_1_1 = instance.weighted_moments_normalized[0, 0]
        self.moments_weighted_normalized_1_2 = instance.weighted_moments_normalized[0, 1]
        self.moments_weighted_normalized_1_3 = instance.weighted_moments_normalized[0, 2]
        self.moments_weighted_normalized_2_1 = instance.weighted_moments_normalized[1, 0]
        self.moments_weighted_normalized_2_2 = instance.weighted_moments_normalized[1, 1]
        self.moments_weighted_normalized_2_3 = instance.weighted_moments_normalized[1, 2]
        self.moments_weighted_normalized_3_1 = instance.weighted_moments_normalized[2, 0]
        self.moments_weighted_normalized_3_2 = instance.weighted_moments_normalized[2, 1]
        self.moments_weighted_normalized_3_3 = instance.weighted_moments_normalized[2, 2]

        self.moments_weighted_spatial_1_1 = instance.weighted_moments[0, 0]
        self.moments_weighted_spatial_1_2 = instance.weighted_moments[0, 1]
        self.moments_weighted_spatial_1_3 = instance.weighted_moments[0, 2]
        self.moments_weighted_spatial_2_1 = instance.weighted_moments[1, 0]
        self.moments_weighted_spatial_2_2 = instance.weighted_moments[1, 1]
        self.moments_weighted_spatial_2_3 = instance.weighted_moments[1, 2]
        self.moments_weighted_spatial_3_1 = instance.weighted_moments[2, 0]
        self.moments_weighted_spatial_3_2 = instance.weighted_moments[2, 1]
        self.moments_weighted_spatial_3_3 = instance.weighted_moments[2, 2]

        self.orientation = instance.orientation

        self.perimeter = instance.perimeter

        self.solidity = instance.solidity
